### ISSUE TITLE
Storm版本

### ISSUE THREAD

**Issue by dk900912** [chimney-lee/rpmbuild1.4.z#1]
Storm集群我看了下版本号是：1.1.0-bc1.4.0，Storm官方Release日志中的确有1.1.0版本，我就是想单纯的确认一下你们是基于1.1.0封装的吧

**Comment by chimney-lee** [comment]
是的，基于开源1.1.0

**Comment by dk900912** [comment]
@chimney-lee 谢谢啦 同事！！！
